on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  sync-comment-in-asana-task-job:
    runs-on: ubuntu-latest
    name: Sync a comment in Asana Task
    steps:
      - name: Sync a comment
        uses: nsquared-team/asana-comment-on-task-github-action@main
        id: syncComment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
          comment-text: "PR #{{PR_ID}} {{PR_NAME}} is {{PR_STATE}} -> {{PR_URL}}"
      - name: Get status
        run: echo "Status is ${{ steps.syncComment.outputs.status }}"
